version: "2.1"
services:
  mongo:
    image: mongo
  api:
    build: ./api
    image: otomato/maskshop-api:${TAG-latest}
    ports:
    - 8888:80
  front:
    build: ./front
    image: otomato/maskshop-front:${TAG-latest}
    environment:
      - INITDB=true
    ports:
    - 8880:80
